apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    url: http://victoriametrics:8428
    isDefault: true
    access: proxy
    jsonData:
      httpMethod: POST

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
